# study area extent definition
mode: ref # ref | aoi | tiles
crs: ''
extent:
  # when mode=ref provide:
  default_input_dpath: '${execution.exp_root}/input/extent_reference'
  filename: ''
  filepath: ''
  # when mode=(aoi | tiles) provide:
  origin: [0.0, 0.0] # x, y in CRS units
  pixel_size: [0.0, 0.0] # x, y positive magnitudes; we assume north up
  # when mode=aoi
  grid_extent: [0.0, 0.0] # height and width in CRS units
  # when mode=tiles
  grid_shape: [0, 0] # rows and cols as number of tiles
# specs
tile_specs:
  size_row: 256
  size_col: 256
  overlap_row: 0
  overlap_col: 0
