# configuration for building multihead model
model_body: unet
model_body_registry:

  unet:
    body: unet
    base_ch: 32
    conv_params:
      downs:
        norm: gn
        gn_groups: 8
        p_drop: 0.0
      ups:
        norm: gn
        gn_groups: 8
        p_drop: 0.0

  unetpp:
    body: unetpp
    base_ch: 32
    conv_params:
      downs:
        norm: gn
        gn_groups: 8
        p_drop: 0.0
      nodes:
        norm: gn
        gn_groups: 8
        p_drop: 0.0

  unetppp:
    body: unetpp
    base_ch: 32
    conv_params:
      downs:
        norm: gn
        gn_groups: 8
        p_drop: 0.0
      nodes:
        norm: gn
        gn_groups: 8
        p_drop: 0.0

# conditioning
conditioner: [concat, film]
conditioner_registry:

  concat:
    name: concat
    use_ids: True
    use_vec: True
    ids_embd_dims: int = 4
    vec_proj_dims: int = 4
    vec_proj_config:
      use_mlp: False

  film:
    name: film
    use_ids: True
    use_vec: True
    ids_embd_dims: int = 4
    vec_proj_dims: int = 4
    vec_proj_config:
      use_mlp: True
      hidden_dim: 256
      num_layers: 1
      activation: 'gelu'
      dropout: 0.1

# numerical safety
enable_clamp: True
clamp_range: [1e-4, 1e4]
