# backbone
model_body: unet
model_body_registry:

  unet:
    body: unet
    base_ch: 32
    encoder_conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0
    nodes_conv_params: null
    decoder_conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0

  unetpp:
    body: unetpp
    base_ch: 32
    encoder_conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0
    nodes_conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0
    decoder_conv_params: null

  unetppp:
    body: unetppp
    base_ch: 32
    encoder_conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0
    nodes_conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0
    decoder_conv_params: null

# bottlenecks
bottleneck: conv
bottleneck_registry:

  conv:
    variant: conv
    num_conv_blocks: null
    conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0
    num_transformer_blocks: null
    transformer_params: null

  transformer:
    variant: transformer
    num_conv_blocks: null
    conv_params: null
    num_transformer_blocks: 4
    transformer_params:
      num_heads: 8
      mlp_ratio: 0.1
      dropout: 0.05
      attn_dropout: 0.0

  hybrid:
    variant: hybrid
    num_conv_blocks: 2
    conv_params:
      norm: gn
      gn_groups: 8
      p_drop: 0.0
    num_transformer_blocks: 4
    transformer_params:
      num_heads: 8
      mlp_ratio: 0.1
      dropout: 0.05
      attn_dropout: 0.0

# conditioning
conditioners: [concat, film]
conditioner_registry:

  concat:
    name: concat
    use_ids: True
    use_vec: True
    ids_embd_dims: 4
    vec_proj_dims: 4
    vec_proj_config:
      use_mlp: False
    conditioner_config: {}

  film:
    name: film
    use_ids: True
    use_vec: True
    ids_embd_dims: 4
    vec_proj_dims: 4
    vec_proj_config:
      use_mlp: True
      hidden_dim: 128
      num_layers: 1
      activation: 'silu'
      dropout: 0.1
    conditioner_config:
      hidden_dim: 128

# safety
numeric_safety:
  enable_clamp: True
  clamp_range: [1e-4, 1e4]
