# experiment config
ckpt_dpath: ${exp_root}/checkpoints
preview_dpath: ${exp_root}/previews

# training phases
phases:
  # example phase
    - name: coarse_head
      num_epochs: 50
      heads:
        active_heads: [layer1]
        frozen_heads: null
        excluded_cls: null
      logit_adjust:
        logit_adjust_alpha: 1.0
        enable_train_logit_adjustment: False
        enable_val_logit_adjustment: False
        enable_test_logit_adjustment: False
      lr_scale: 1.0