# Main entry to the config tree
defaults:
  - _self_
  # raw inputs
  - input_extent: demo
  - input_domain: demo
  - input_data: demo
  # preparation
  - prep_grid: default
  - prep_domain: default
  - prep_data: default
  # model & trainer
  - models: default
  - trainer: default
  # experiment
  - experiment: demo
  - profile: end_to_end

# experiment root
exp_root: ./experiment

# dev-facing local override; optional and untracked
dev_settings_path: ${oc.env:AUX_SETTINGS_PATH, null}

# hydra settings
hydra:
  run:
    dir: .
  output_subdir: null