# Main entry to the config tree
defaults:
  - _self_
  # data foundation
  - foundation/grid: default
  - foundation/domains: default
  - foundation/datablocks: default
  # data transfrom
  - transform: default
  # data specs
  - dataspecs: default
  # models
  - models: default
  # session
  - session/components: default
  - session/runtime: default
  - session/phases: default
  # pipeline
  - pipeline: default

# experiment root
exp_root: ./experiment

# dev-facing local override; optional and untracked
dev_settings_path: ${oc.env:AUX_SETTINGS_PATH, null}

# hydra settings
hydra:
  run:
    dir: .
  output_subdir: null