# Main entry to the config tree
defaults:
  - _self_
  # raw inputs
  - inputs/extent: demo
  - inputs/domain: demo
  - inputs/data: demo
  # preparation
  - prep/grid: default
  - prep/domain: default
  - prep/data: default
  # models
  - models: default
  # trainer
  - trainer: default
  # controller
  - runner: demo
  # profile
  - profile: default

# experiment root
exp_root: ./experiment

# dev-facing local override; optional and untracked
dev_settings_path: ${oc.env:AUX_SETTINGS_PATH, null}

# hydra settings
hydra:
  run:
    dir: .
  output_subdir: null