# =========================================================================== #
#           Copyright (c) His Majesty the King in right of Ontario,           #
#         as represented by the Minister of Natural Resources, 2026.          #
#                                                                             #
#                      © King's Printer for Ontario, 2026.                    #
#                                                                             #
#       Licensed under the Apache License, Version 2.0 (the 'License');       #
#          you may not use this file except in compliance with the            #
#                                  License.                                   #
#                  You may obtain a copy of the License at:                   #
#                                                                             #
#                  http://www.apache.org/licenses/LICENSE-2.0                 #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#     distributed under the License is distributed on an 'AS IS' BASIS,       #
#      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        #
#                                   implied.                                  #
#       See the License for the specific language governing permissions       #
#                       and limitations under the License.                    #
# =========================================================================== #

# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=too-few-public-methods

'''
Callback classes protocols
'''

# standard imports
from __future__ import annotations
import typing

# ----------------------------------callbacks----------------------------------
@typing.runtime_checkable
class CallBacksLike(typing.Protocol):
    @property
    def train(self) -> _TrainCallbackLike:...
    @property
    def validate(self) -> _ValCallbackLike:...
    @property
    def infer(self) -> _InferCallbackLike:...
    @property
    def logging(self) -> _LoggingCallbackLike:...
    @property
    def progress(self) -> _ProgressCallbackLike:...
    def __iter__(self) -> typing.Iterator[_CallBackBaseLike]: ...

@typing.runtime_checkable
class _CallBackBaseLike(typing.Protocol):
    def setup(self, state, config, *, device, skip_log: bool) -> None: ...

@typing.runtime_checkable
class _ProgressCallbackLike(typing.Protocol):
    def on_train_epoch_begin(self, epoch: int) -> None: ...
    def on_train_batch_end(self) -> None: ...
    def on_train_epoch_end(self) -> None: ...
    def on_validation_begin(self) -> None: ...
    def on_validation_end(self) -> None: ...

@typing.runtime_checkable
class _TrainCallbackLike(typing.Protocol):
    def on_train_epoch_begin(self, epoch: int) -> None: ...
    def on_train_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_train_batch_forward(self) -> None: ...
    def on_train_batch_compute_loss(self) -> None: ...
    def on_train_backward(self) -> None: ...
    def on_train_before_optimizer_step(self) -> None: ...
    def on_train_optimizer_step(self) -> None: ...
    def on_train_batch_end(self) -> None: ...
    def on_train_epoch_end(self) -> None: ...

@typing.runtime_checkable
class _ValCallbackLike(typing.Protocol):
    def on_validation_begin(self) -> None: ...
    def on_validation_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_validation_batch_forward(self) -> None: ...
    def on_validation_batch_end(self) -> None: ...
    def on_validation_end(self) -> None: ...

@typing.runtime_checkable
class _InferCallbackLike(typing.Protocol):
    def on_inference_begin(self) -> None: ...
    def on_inference_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_inference_batch_forward(self) -> None: ...
    def on_inference_batch_end(self) -> None: ...
    def on_inference_end(self, out_dir: str) -> None: ...

@typing.runtime_checkable
class _LoggingCallbackLike(typing.Protocol):
    def on_train_epoch_begin(self, epoch: int) -> None: ...
    def on_train_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_train_batch_end(self) -> None: ...
    def on_train_epoch_end(self) -> None: ...
    def on_validation_begin(self) -> None: ...
    def on_validation_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_validation_end(self) -> None: ...
