# =========================================================================== #
#           Copyright (c) His Majesty the King in right of Ontario,           #
#         as represented by the Minister of Natural Resources, 2026.          #
#                                                                             #
#                      © King's Printer for Ontario, 2026.                    #
#                                                                             #
#       Licensed under the Apache License, Version 2.0 (the 'License');       #
#          you may not use this file except in compliance with the            #
#                                  License.                                   #
#                  You may obtain a copy of the License at:                   #
#                                                                             #
#                  http://www.apache.org/licenses/LICENSE-2.0                 #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#     distributed under the License is distributed on an 'AS IS' BASIS,       #
#      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        #
#                                   implied.                                  #
#       See the License for the specific language governing permissions       #
#                       and limitations under the License.                    #
# =========================================================================== #

# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=too-few-public-methods
'''
Trainer building facing components protocols.
'''

# standard imports
from __future__ import annotations
import typing

if typing.TYPE_CHECKING:
    import torch

# -----------------------------Engine components-----------------------------
@typing.runtime_checkable
class ComponentsLike(typing.Protocol):
    @property
    def callbacks(self) -> _CallBacksLike:...
    @property
    def dataloaders(self) -> _DataLoadersLike:...
    @property
    def headspecs(self) -> _HeadSpecsLike:...
    @property
    def headlosses(self) -> _HeadLossesLike:...
    @property
    def headmetrics(self) -> _HeadMetricsLike:...
    @property
    def optimization(self) -> _OptimizationLike:...

# ---------------------------------dataloaders---------------------------------
@typing.runtime_checkable
class _DataLoadersLike(typing.Protocol):
    @property
    def train(self) -> 'torch.utils.data.DataLoader':...
    @property
    def val(self) -> 'torch.utils.data.DataLoader':...
    @property
    def test(self) -> 'torch.utils.data.DataLoader | None':...
    @property
    def meta(self) -> _LoaderMetaLike: ...

class _LoaderMetaLike(typing.Protocol):
    batch_size: int
    patch_per_blk: int
    test_blks_grid: tuple[int, int]

# ---------------------------------head  specs---------------------------------
@typing.runtime_checkable
class _HeadSpecsLike(typing.Protocol):
    def __getitem__(self, key: str) -> SpecsLike: ...
    def __len__(self) -> int: ...
    def as_dict(self) -> typing.Mapping[str, SpecsLike]: ...

@typing.runtime_checkable
class SpecsLike(typing.Protocol):
    @property
    def name(self) -> str:...
    @property
    def count(self) -> list[int]:...
    @property
    def loss_alpha(self) -> list[float]:...
    @property
    def parent_head(self) -> str | None:...
    @property
    def parent_cls(self) -> int | None:...
    @property
    def weight(self) -> float:...
    @property
    def exclude_cls(self) -> tuple[int, ...]:...
    @property
    def num_classes(self) -> int:...
    def set_exclude(self, indices: tuple[int, ...]) -> None:...

# ----------------------------------head loss----------------------------------
@typing.runtime_checkable
class _HeadLossesLike(typing.Protocol):
    def __getitem__(self, key: str) -> CompositeLossLike: ...
    def __len__(self) -> int: ...
    def as_dict(self) -> typing.Mapping[str, CompositeLossLike]: ...

@typing.runtime_checkable
class CompositeLossLike(typing.Protocol):
    @property
    def ignore_index(self) -> int:...
    def forward(self, p: 'torch.Tensor', t: 'torch.Tensor', **kwargs) -> 'torch.Tensor': ...

# --------------------------------head  metrics--------------------------------
@typing.runtime_checkable
class _HeadMetricsLike(typing.Protocol):
    def __getitem__(self, key: str) -> ConfusionMatrixLike: ...
    def __len__(self) -> int: ...
    def as_dict(self) -> typing.Mapping[str, ConfusionMatrixLike]: ...

@typing.runtime_checkable
class ConfusionMatrixLike(typing.Protocol):
    exclude_class_1b: tuple[int, ...] | None
    @property
    def metrics_dict(self) -> dict[str, typing.Any]: ...
    @property
    def metrics_text(self) -> list[str]: ...
    def update(self, preds: 'torch.Tensor', targets: 'torch.Tensor', **kwargs) -> None: ...
    def compute(self) -> None: ...
    def reset(self, device: str) -> None: ...

# ------------------------------------optim------------------------------------
@typing.runtime_checkable
class _OptimizationLike(typing.Protocol):
    optimizer: torch.optim.Optimizer
    scheduler: torch.optim.lr_scheduler.LRScheduler | None

# ----------------------------------callbacks----------------------------------
@typing.runtime_checkable
class _CallBacksLike(typing.Protocol):
    @property
    def train(self) -> _TrainCallbackLike:...
    @property
    def validate(self) -> _ValCallbackLike:...
    @property
    def infer(self) -> _InferCallbackLike:...
    @property
    def logging(self) -> _LoggingCallbackLike:...
    @property
    def progress(self) -> _ProgressCallbackLike:...
    def __iter__(self) -> typing.Iterator[_CallBackBaseLike]: ...

@typing.runtime_checkable
class _CallBackBaseLike(typing.Protocol):
    def setup(self, state, config, *, device, skip_log: bool) -> None: ...

@typing.runtime_checkable
class _ProgressCallbackLike(typing.Protocol):
    def on_train_epoch_begin(self, epoch: int) -> None: ...
    def on_train_batch_end(self) -> None: ...
    def on_train_epoch_end(self) -> None: ...
    def on_validation_begin(self) -> None: ...
    def on_validation_end(self) -> None: ...

@typing.runtime_checkable
class _TrainCallbackLike(typing.Protocol):
    def on_train_epoch_begin(self, epoch: int) -> None: ...
    def on_train_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_train_batch_forward(self) -> None: ...
    def on_train_batch_compute_loss(self) -> None: ...
    def on_train_backward(self) -> None: ...
    def on_train_before_optimizer_step(self) -> None: ...
    def on_train_optimizer_step(self) -> None: ...
    def on_train_batch_end(self) -> None: ...
    def on_train_epoch_end(self) -> None: ...

@typing.runtime_checkable
class _ValCallbackLike(typing.Protocol):
    def on_validation_begin(self) -> None: ...
    def on_validation_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_validation_batch_forward(self) -> None: ...
    def on_validation_batch_end(self) -> None: ...
    def on_validation_end(self) -> None: ...

@typing.runtime_checkable
class _InferCallbackLike(typing.Protocol):
    def on_inference_begin(self) -> None: ...
    def on_inference_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_inference_batch_forward(self) -> None: ...
    def on_inference_batch_end(self) -> None: ...
    def on_inference_end(self, out_dir: str) -> None: ...

@typing.runtime_checkable
class _LoggingCallbackLike(typing.Protocol):
    def on_train_epoch_begin(self, epoch: int) -> None: ...
    def on_train_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_train_batch_end(self) -> None: ...
    def on_train_epoch_end(self) -> None: ...
    def on_validation_begin(self) -> None: ...
    def on_validation_batch_begin(self, bidx: int, batch: tuple) -> None: ...
    def on_validation_end(self) -> None: ...
