# =========================================================================== #
#           Copyright (c) His Majesty the King in right of Ontario,           #
#         as represented by the Minister of Natural Resources, 2026.          #
#                                                                             #
#                      © King's Printer for Ontario, 2026.                    #
#                                                                             #
#       Licensed under the Apache License, Version 2.0 (the 'License');       #
#          you may not use this file except in compliance with the            #
#                                  License.                                   #
#                  You may obtain a copy of the License at:                   #
#                                                                             #
#                  http://www.apache.org/licenses/LICENSE-2.0                 #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#     distributed under the License is distributed on an 'AS IS' BASIS,       #
#      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        #
#                                   implied.                                  #
#       See the License for the specific language governing permissions       #
#                       and limitations under the License.                    #
# =========================================================================== #

# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=too-few-public-methods

'''
Shared runtime state for a session.
'''

# standard imports
from __future__ import annotations
import typing
# local imports
import landseg.session.common as common
import landseg.session.common.alias as alias

if typing.TYPE_CHECKING:
    import torch

# ----- Runtime state (composite)
@typing.runtime_checkable
class StateLike(typing.Protocol):
    @property
    def progress(self) -> _Progress: ...
    @property
    def heads(self) -> _Heads: ...
    @property
    def batch_cxt(self) -> _BatchContex: ...
    @property
    def batch_out(self) -> _BatchOutput: ...
    @property
    def summary(self) -> _EpochSummary: ...
    @property
    def optim(self) -> _OptimState: ...

class _Progress(typing.Protocol):
    @property
    def epoch(self) -> int: ...
    @property
    def epoch_step(self) -> int: ...
    @property
    def global_step(self) -> int: ...
    @property
    def current_metrics(self) -> float: ...

class _Heads(typing.Protocol):
    @property
    def all_heads(self) -> list[str]: ...
    @property
    def active_heads(self) -> list[str] | None: ...
    @property
    def frozen_heads(self) -> list[str] | None: ...
    @property
    def active_hspecs(self) -> dict[str, common.SpecsLike] | None: ...
    @property
    def active_hloss(self) -> dict[str, common.CompositeLossLike] | None: ...
    @property
    def active_hmetrics(self) -> dict[str, common.ConfusionMatrixLike] | None: ...

class _BatchContex(typing.Protocol):
    @property
    def bidx(self) -> int: ...
    @property
    def pidx_start(self) -> int: ...
    @property
    def batch(self) -> alias.DatasetItem | None: ...
    @property
    def batch_size_full(self) -> int: ...
    @property
    def x(self) -> torch.Tensor: ...
    @property
    def y_dict(self) -> dict[str, torch.Tensor]: ...
    @property
    def domain(self) -> dict[str, torch.Tensor | None]: ...
    def refresh(self, bidx: int, batch: tuple) -> None: ...

class _BatchOutput(typing.Protocol):
    @property
    def bidx(self) -> int: ...
    @property
    def preds(self) -> dict[str, torch.Tensor]: ...
    @property
    def total_loss(self) -> torch.Tensor: ...
    @property
    def head_loss(self) -> dict[str, float]: ...
    def refresh(self, bidx) -> None: ...

class _EpochSummary(typing.Protocol):
    @property
    def train_summary(self) -> _TrainSummary: ...
    @property
    def val_summary(self) -> _ValSummary: ...
    @property
    def infer_context(self) -> _InferContext: ...

class _TrainSummary(typing.Protocol):
    @property
    def total_loss(self) -> float: ...
    @property
    def head_losses_str(self) -> str: ...
    @property
    def updated(self) -> bool: ...
    def clear(self) -> None: ...

class _ValSummary(typing.Protocol):
    @property
    def target_metrics(self) -> float: ...
    @property
    def head_metrics_str(self) -> dict[str, list[str]]: ...
    def clear(self) -> None: ...

class _InferContext(typing.Protocol):
    @property
    def patch_per_blk(self) -> int: ...
    @property
    def patch_per_dim(self) -> int: ...
    @property
    def block_columns(self) -> int: ...
    @property
    def patch_grid_shape(self) -> tuple[int, int]: ...
    @property
    def maps(self) -> dict[str, dict[tuple[int, int], torch.Tensor]]: ...

class _OptimState(typing.Protocol):
    @property
    def scaler(self) -> torch.GradScaler: ...
