# =========================================================================== #
#           Copyright (c) His Majesty the King in right of Ontario,           #
#         as represented by the Minister of Natural Resources, 2026.          #
#                                                                             #
#                      © King's Printer for Ontario, 2026.                    #
#                                                                             #
#       Licensed under the Apache License, Version 2.0 (the 'License');       #
#          you may not use this file except in compliance with the            #
#                                  License.                                   #
#                  You may obtain a copy of the License at:                   #
#                                                                             #
#                  http://www.apache.org/licenses/LICENSE-2.0                 #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#     distributed under the License is distributed on an 'AS IS' BASIS,       #
#      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        #
#                                   implied.                                  #
#       See the License for the specific language governing permissions       #
#                       and limitations under the License.                    #
# =========================================================================== #

'''
Canonical data blocks catalog and metadata typing utilities.

This module defines the core data structures used to represent, validate,
and serialize a catalog of spatial data blocks generated by a geospatial
data preparation pipeline.

It provides:

- `CatalogEntry`: A strongly-typed dictionary describing metadata for a
  single spatial block, including file locations, spatial indices,
  statistical summaries, provenance hashes, and lineage information.

- `BlocksCatalog`: A dictionary-like container that maps (row, col)
  spatial indices to `CatalogEntry` objects. It supports deterministic
  serialization, reconstruction from persisted data, and controlled
  mutation while maintaining a consistent schema.

These abstractions ensure reproducibility, type safety, and stable data
exchange across different stages of the pipeline.
'''

# standard imports
from __future__ import annotations
import collections.abc
import json
import typing

# ---------------------------------Public Type---------------------------------
class CatalogEntry(typing.TypedDict):
    '''
    Typed dictionary representing metadata for a single data block.

    Each entry captures both structural and provenanceinformation
    required to uniquely identify, validate, and reproduce a block.

    Fields:

    - **block_name**:
        Human-readable identifier for the block.
    - **file_path**:
        Absolute or relative path to the stored block file.
    - **row_col**:
        Two-element list representing the (row, col) grid index.
    - **base_valid_px**:
         Fraction or count of valid pixels in the base raster.
    - **base_class_count**:
         Per-class pixel counts for the base classification.
    - **schema_version**:
         Version identifier for the metadata schema.
    - **creation_time**:
         ISO-formatted timestamp indicating when the block was created.
    - **sha_256**:
         SHA-256 hash of the block file for integrity verification.
    - **aligned_grid**:
         Identifier for the grid system used for alignment.
    - **source_image**:
         Path or identifier of the source imagery.
    - **source_image_sha_256**:
         SHA-256 hash of the source image.
    - **source_label**:
         Optional path or identifier for the source label data.
    - **source_label_sha_256**:
         Optional SHA-256 hash of the source label data.
    '''
    block_name: str
    file_path: str
    row_col: list[int]
    base_valid_px: float
    base_class_count: list[int]
    schema_version: str
    creation_time: str
    sha_256: str
    aligned_grid: str
    source_image: str
    source_image_sha_256: str
    source_label: str | None
    source_label_sha_256: str | None

# --------------------------------Public  Class--------------------------------
class DataCatalog(collections.abc.Mapping[tuple[int, int], CatalogEntry]):
    '''
    Mapping container for managing spatial block metadata.

    This class provides a dictionary-like interface that maps (row, col)
    coordinate tuples to `CatalogEntry` objects. While it conforms to the
    read-only `Mapping` interface, it also supports controlled mutation
    via item assignment.

    Key features:
        - Spatial indexing using (row, col) keys
        - Deterministic iteration and serialization
        - Lightweight access to derived views (e.g., file paths)
        - Reconstruction from persisted dictionary/JSON data

    Notes: Internally, data is stored in a standard Python dictionary.
    Deterministic serialization is achieved by sorting keys prior to
    output.

    **Schema**: `SCHEMA_ID` = `'data_catalog_payload/v1'`
    '''

    SCHEMA_ID: str = 'data_catalog_payload/v1'

    def __init__(self) -> None:
        self._data: dict[tuple[int, int], CatalogEntry] = {}

    # ----- container protocol
    def __getitem__(self, key: tuple[int, int]) -> CatalogEntry:
        return self._data[key]

    def __setitem__(self, key: tuple[int, int], value):
        self._data[key] = value

    def __iter__(self) -> collections.abc.Iterator[tuple[int, int]]:
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    # ----- alternative constructor
    @classmethod
    def from_dict(cls, source: dict[str, CatalogEntry]) -> DataCatalog:
        '''
        Construct a `BlocksCatalog` from a dictionary representation.

        The input is expected to use string-encoded coordinate keys,
        which are converted back into (row, col) tuples.

        Args:
            source:
                Dictionary mapping string keys (e.g., "x_y") to
                `CatalogEntry` objects.

        Returns:
            A populated `BlocksCatalog` instance.
        '''

        def _name_xy(name: str) -> tuple[int, int]:
            # e.g.,  row_000034_col_000012 -> (12, 34)
            split = name.split('_')
            y_str, x_str = split[1], split[3]
            return int(x_str), int(y_str)

        obj = cls.__new__(cls)
        obj._data = {_name_xy(k): v for k, v in source.items()}
        return obj

    def to_json_payload(self) -> str:
        '''
        Serialize the catalog to a deterministically ordered JSON string.

        The output is formatted with custom indentation and stable key
        ordering to ensure reproducibility across runs.

        Returns:
            A formatted JSON string representing the catalog.
        '''

        def _xy_name(coords: tuple[int, int]) -> str:
            # e.g., (12, 34) -> row_000034_col_000012
            x, y = coords
            return f'row_{y:06d}_col_{x:06d}'

        # sort self._data and start the line
        data = {_xy_name(k): v for k, v in self._data.items()}
        items = sorted(data.items())
        lines = ['{']
        # manual formatting line-by-line
        for i, (key, value) in enumerate(items):
            blk_txt = json.dumps(value)
            blk_txt = blk_txt.replace('{', '{\n\t\t')
            blk_txt = blk_txt.replace(', "', ',\n\t\t"')
            blk_txt = blk_txt.replace('}', '\n\t}')

            line = f'\t"{key}": {blk_txt}'
            if i < len(items) - 1:
                line += ','
            lines.append(line)

        lines.append('}')
        return '\n'.join(lines)
