# =========================================================================== #
#           Copyright (c) His Majesty the King in right of Ontario,           #
#         as represented by the Minister of Natural Resources, 2026.          #
#                                                                             #
#                      © King's Printer for Ontario, 2026.                    #
#                                                                             #
#       Licensed under the Apache License, Version 2.0 (the 'License');       #
#          you may not use this file except in compliance with the            #
#                                  License.                                   #
#                  You may obtain a copy of the License at:                   #
#                                                                             #
#                  http://www.apache.org/licenses/LICENSE-2.0                 #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#     distributed under the License is distributed on an 'AS IS' BASIS,       #
#      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        #
#                                   implied.                                  #
#       See the License for the specific language governing permissions       #
#                       and limitations under the License.                    #
# =========================================================================== #

# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=too-few-public-methods
# pylint: disable=too-many-public-methods

'''
Protocols for root config dataclass.
'''

# standard imports
from __future__ import annotations
import typing

#
class RootConfigShape(typing.Protocol):
    @property
    def pipeline(self) -> _Pipeline: ...
    @property
    def study(self) -> _StudyObjectives: ...
    # setter methods
    # ----- data geometry
    def set_data_patch_size(self, patch_size: int) -> None: ...
    def set_data_batch_size(self, batch_size: int) -> None: ...
    # ----- runtime optimization
    def set_optimizer_lr(self, lr: float) -> None: ...
    def set_optimizer_weight_decay(self, weight_decay: float) -> None: ...
    def set_optimizer_type(self, opt_cls: str) -> None: ...
    def set_optimizer_scheduler_type(self, sched_cls: str | None) -> None: ...
    def set_optimizer_scheduler_args(self, sched_args: dict[str, typing.Any]) -> None: ...
    def set_optimizer_grad_clip_norm(self, grad_clip_norm: float | None,) -> None: ...
    def set_runtime_use_amp(self, use_amp: bool) -> None: ...
    def set_runtime_logit_adjust_alpha(self, alpha: float) -> None: ...
    # ----- objective (loss + regularization)
    def set_objective_focal_weight(self, weight: float) -> None: ...
    def set_objective_dice_weight(self, weight: float) -> None: ...
    def set_objective_spectral_weight(self, weight: float) -> None: ...
    def set_objective_tv_weight(self, weight: float) -> None: ...
    # ----- multitask
    def set_mtl_consistency_lambda(self, value: float) -> None: ...
    def set_mtl_consistency_reduction(self, reduction: str) -> None: ...
    # ----- architecture
    def set_model_body(self, model_body: str) -> None: ...
    def set_model_base_channel(self, base_channel: int) -> None: ...
    def set_model_bottleneck(self, bottleneck: str) -> None: ...
    def set_model_conditioners(self, conditioners: list[str]) -> None: ...
    # ----- bottleneck structure (architecture sub-domain)
    def set_bottleneck_convolution_blocks(self, num_blocks: int | None) -> None: ...
    def set_bottleneck_transformer_blocks(self, num_blocks: int | None) -> None: ...
    # ----- transformer parameters (architecture sub-domain)
    def set_transformer_num_heads(self, num_heads: int) -> None: ...
    def set_transformer_mlp_ratio(self, mlp_ratio: float) -> None: ...
    def set_transformer_dropout(self, dropout: float) -> None: ...
    def set_transformer_attn_dropout(self, attn_dropout: float) -> None: ...

#
class _Pipeline(typing.Protocol):
    @property
    def study_sweep(self) -> _StudySweep: ...

class _StudySweep(typing.Protocol):
    @property
    def study_name(self) -> str: ...
    @property
    def preset_name(self) -> str: ...
    @property
    def storage(self) -> str: ...
    @property
    def direction(self) -> str: ...
    @property
    def n_trials(self) -> int: ...
    @property
    def seed(self) -> int: ...

class _StudyObjectives(typing.Protocol):
    @property
    def base(self) -> _BaseObjectives: ...
    @property
    def optimizer(self) -> _OptimizerObjectives: ...
    @property
    def throughput(self) -> _ThroughputObjectives: ...
    @property
    def data_geometry(self) -> _DataGeometryObjectives: ...
    @property
    def context_window(self) -> _ContextWindowObjectives: ...
    @property
    def architecture(self) -> _ArchitectureObjectives: ...
    @property
    def bottleneck(self) -> _BottleneckObjectives: ...
    @property
    def conditioning(self) -> _ConditioningObjectives: ...
    @property
    def loss_balance(self) -> _LossBalanceObjectives: ...
    @property
    def loss_auxiliary(self) -> _LossAuxiliaryObjectives: ...
    @property
    def regularization(self) -> _RegularizationObjectives: ...
    @property
    def head_weights(self) -> _HeadWeightsObjectives: ...
    @property
    def mtl_joint(self) -> _MtlJointObjectives: ...
    @property
    def hierarchy(self) -> _HierarchyObjectives: ...

class _BaseObjectives(typing.Protocol):
    @property
    def learning_rate(self) -> tuple[float, float]: ...
    @property
    def batch_size(self) -> tuple[int, int, int]: ...

class _OptimizerObjectives(typing.Protocol):
    @property
    def learning_rate(self) -> tuple[float, float]: ...
    @property
    def weight_decay(self) -> tuple[float, float]: ...

class _ThroughputObjectives(typing.Protocol):
    @property
    def batch_size(self) -> tuple[int, int, int]: ...
    @property
    def use_amp(self) -> list[bool]: ...

class _DataGeometryObjectives(typing.Protocol):
    @property
    def patch_size(self) -> tuple[int, int, int]: ...
    @property
    def batch_size(self) -> tuple[int, int, int]: ...

class _ContextWindowObjectives(typing.Protocol):
    @property
    def patch_size(self) -> tuple[int, int, int]: ...

class _ArchitectureObjectives(typing.Protocol):
    @property
    def model_body(self) -> list[str]: ...
    @property
    def base_channel(self) -> tuple[int, int, int]: ...
    @property
    def bottleneck(self) -> list[str]: ...

class _BottleneckObjectives(typing.Protocol):
    @property
    def bottleneck(self) -> list[str]: ...
    @property
    def num_conv_blocks(self) -> tuple[int, int, int]: ...
    @property
    def num_transformer_blocks(self) -> tuple[int, int, int]: ...
    @property
    def num_heads(self) -> list[int]: ...
    @property
    def mlp_ratio(self) -> tuple[float, float]: ...
    @property
    def dropout(self) -> tuple[float, float]: ...
    @property
    def attn_dropout(self) -> tuple[float, float]: ...

class _ConditioningObjectives(typing.Protocol):
    @property
    def conditioners(self) -> list[list[str]]: ...

class _LossBalanceObjectives(typing.Protocol):
    @property
    def focal_weight(self) -> tuple[float, float]: ...
    @property
    def dice_weight(self) -> tuple[float, float]: ...

class _LossAuxiliaryObjectives(typing.Protocol):
    @property
    def spectral_weight(self) -> tuple[float, float]: ...
    @property
    def tv_weight(self) -> tuple[float, float]: ...

class _RegularizationObjectives(typing.Protocol):
    @property
    def consistency_lambda(self) -> tuple[float, float]: ...

class _HeadWeightsObjectives(typing.Protocol):
    @property
    def logit_adjust_alpha(self) -> tuple[float, float]: ...

class _MtlJointObjectives(typing.Protocol):
    @property
    def consistency_lambda(self) -> tuple[float, float]: ...
    @property
    def logit_adjust_alpha(self) -> tuple[float, float]: ...

class _HierarchyObjectives(typing.Protocol):
    @property
    def consistency_lambda(self) -> tuple[float, float]: ...
    @property
    def consistency_reduction(self) -> list[str]: ...
