# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=too-few-public-methods
'''
Callback-facing trainer class protocols. Mimics related behaviours.
'''

# standard imports
from __future__ import annotations
import typing
# local imports
import training.common

# -------------------------------trainer class-------------------------------
@typing.runtime_checkable
class TrainerLike(typing.Protocol):
    comps: training.common.TrainerComponentsLike
    config: training.common.RuntimeConfigLike
    state: training.common.RuntimeStateLike
    device: str
    # def set_head_state(self, active_heads, frozen_heads, excluded_cls ) -> None: ...
    # def reset_head_state(self) -> None: ...
    # def train_one_epoch(self, epoch: int) -> dict[str, float]: ...
    def validate(self) -> dict[str, typing.Any]: ...
    def _parse_batch(self) -> None: ...
    def _autocast_ctx(self) -> typing.ContextManager: ...
    def _val_ctx(self) -> typing.ContextManager: ...
    def _compute_loss(self) -> None: ...
    def _update_train_logs(self, bidx: int, flush: bool=True) -> bool: ...
    def _update_conf_matrix(self) -> None: ...
    def _compute_iou(self) -> None: ...
    def _clip_grad(self) -> None: ...
