# @package _global_

models:
  model_body: unet
  conditioners: []

session:

  engine_exec:
    use_amp: False
    logit_adjust_alpha: 0.0

  engine_optim:
    lr: 1e-3
    weight_decay: 0.0
    sched_cls: null
    grad_clip_norm: null

  engine_tasks:
    loss_types:
      focal:
        weight: 0.5
        gamma: 0.0
      dice:
        weight: 0.5
      spectral:
        weight: 0.0
      tv:
        weight: 0.0

  orchestration:
    monitor:
      track_heads: [base]

pipeline:
  name: diagnose-overfit