# @package _global_

models:
  conditioning:
    mode: null
    concat:
      out_dim: 0
      use_ids: False
      use_vec: False
      use_mlp: False
    film:
      embed_dim: 0
      use_ids: False
      use_vec: False
      hidden: 128

trainer:
  optimization:
    lr: 1e-3
    weight_decay: 0.0
    sched_cls: null
    sched_args: {}
  loss:
    types:
      focal:
        weight: 1.0
        gamma: 0.0
      dice:
        weight: 0.0
      spectral:
        weight: 0.1
  runtime:
    schedule:
      max_epoch: 1000
    monitor:
      track_head_name: base
    precision:
      use_amp: False
    optimization:
      grad_clip_norm: null