# name of the dataset
name: demo_data
# input fit data
fit:
  image: ${exp_root}/input/data/fit/image.tif
  label: ${exp_root}/input/data/fit/label.tif
# input test data (optional)
test:
  image: ${exp_root}/input/data/test/image.tif
  label: ${exp_root}/input/data/test/label.tif
# data configuration
config: ${exp_root}/input/data/config.json