# name of the dataset
name: demo_data
# input fit data
fit:
  image: ${exp_root}/input/${dataset.name}/fit/image.tif
  label: ${exp_root}/input/${dataset.name}/fit/label.tif
# input test data (optional)
test:
  image: ${exp_root}/input/${dataset.name}/test/image.tif
  label: ${exp_root}/input/${dataset.name}/test/label.tif
# data configuration
config: ${exp_root}/input/${dataset.name}/config.json